### ISSUE TITLE
OGC CITE fails immediately with added INSPIRE elements in WCS GetCapabilities when testing OGC WCS 2.0.1

### ISSUE THREAD

**Issue by bangph** [opengeospatial/ets-wcs20#107]
I tested OGC CITE on this endpoint http://conformance.rasdaman.com/rasdaman/ows?service=WCS&version=2.0.1&request=GetCapabilities with this session: http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0141&stop=undefined&t=1646391922635

The full log file can be downloaded from: [s0141.zip](https://github.com/opengeospatial/ets-wcs20/files/8185373/s0141.zip)

![image](https://user-images.githubusercontent.com/6914451/156752795-73bc90c6-625b-4c60-b5df-b335d0b69a48.png)

and output error

```
Testing suite wcs2:ets-wcs20 in Test Mode with defaultResult of Pass ...

******************************************************************************************************************************

   Testing wcs2:main type Mandatory in Test Mode with defaultResult Pass (s0141)...

      Assertion: Prune query parameters if present.

Validation error:

  cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.rasdaman.org":sizeInBytes}'. One of '{"http://www.opengis.net/ows/2.0":AbstractMetaData}' is expected.

Validation error:

  cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.rasdaman.org":sizeInBytes}'. One of '{"http://www.opengis.net/ows/2.0":AbstractMetaData}' is expected.

2 validation errors detected.


******************************************************************************************************************************

      Testing wcs2:main_test type Mandatory in Test Mode with defaultResult Pass (s0141/d13242e65_1)...

         Assertion: Test the WCS 2.0.

      Test wcs2:main_test Failed

   Test wcs2:main Failed

Suite wcs2:ets-wcs20 Failed
```

The reason is, because I have extra INSPIRE elements in WCS GetCapabilities (according to INSPIRE standard: https://inspire.ec.europa.eu/documents/Network_Services/Technical_Guidance_Download_Services_3.0.pdf)

```
<ows:ExtendedCapabilities>
        <ows:ExtendedCapabilities>
            <inspire_dls:ExtendedCapabilities>
                <inspire_common:MetadataUrl>
                    <inspire_common:URL>http://conformance.rasdaman.com/rasdaman/ows</inspire_common:URL>
                    <inspire_common:MediaType>application/vnd.iso.19139+xml</inspire_common:MediaType>
                </inspire_common:MetadataUrl>
                <inspire_common:SupportedLanguages>
                    <inspire_common:DefaultLanguage>
                        <inspire_common:Language>eng</inspire_common:Language>
                    </inspire_common:DefaultLanguage>
                </inspire_common:SupportedLanguages>
                <inspire_common:ResponseLanguage>
                    <inspire_common:Language>eng</inspire_common:Language>
                </inspire_common:ResponseLanguage>
            </inspire_dls:ExtendedCapabilities>
</ows:ExtendedCapabilities>
```
The long java error is:

```
Caused by: java.net.MalformedURLException: no protocol: ?SERVICE=WCS&ACCEPTVERSIONS=2.0.1&REQUEST=GetCapabilities
	at java.net.URL.<init>(URL.java:611)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at com.occamlab.te.TECore.build_request(TECore.java:1830)
	at com.occamlab.te.TECore.request(TECore.java:1687)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
	at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
	... 50 more
```

@dstenger @bermud  @ghobona

**Comment by dstenger** [comment]
Thank you for reporting.
We will do further investigation.

**Comment by bangph** [comment]
@dstenger yes, you can test on this: http://conformance.rasdaman.com/rasdaman/ows?service=WCS&version=2.0.1&request=GetCapabilities

**Comment by bpross-52n** [comment]
Both the beta and production tests don't seem to show the reported behavior. I attached the log files. Am I maybe missing something?
[s0085-beta.zip](https://github.com/opengeospatial/ets-wcs20/files/11295317/s0085-beta.zip)
[s0022-production.zip](https://github.com/opengeospatial/ets-wcs20/files/11295319/s0022-production.zip)

**Comment by bangph** [comment]
@bpross-52n  it may be that something changed over time in TeamEngine. I opened this ticket 1 year ago.

**Comment by bpross-52n** [comment]
@bangph Right, we must have accidentally fixed this :slightly_smiling_face: If ok with you, we will close the issue.
