### ISSUE TITLE
Coverages containing large data might lead to an OutOfMemoryError

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs20#130]
Test run via Web Browser Interface never ends (progress page stays).
Stack trace in log file:

```
2d9a80> Exception in thread "Thread-3" java.lang.OutOfMemoryError: Java heap space
2d9a80> 	at java.util.Arrays.copyOf(Arrays.java:3332)
2d9a80> 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
2d9a80> 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
2d9a80> 	at java.lang.StringBuffer.append(StringBuffer.java:270)
2d9a80> 	at org.apache.xerces.dom.DeferredDocumentImpl.getNodeValueString(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.DeferredDocumentImpl.getNodeValueString(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.DeferredTextImpl.synchronizeData(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.CharacterDataImpl.getNodeValue(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.ElementImpl.normalize(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.ElementImpl.normalize(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.ElementImpl.normalize(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.ElementImpl.normalize(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.ElementImpl.normalize(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.ElementImpl.normalize(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.ElementImpl.normalize(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.ElementImpl.normalize(Unknown Source)
2d9a80> 	at org.apache.xerces.dom.ElementImpl.normalize(Unknown Source)
2d9a80> 	at com.occamlab.te.CtlEarlReporter.generateEarlReport(CtlEarlReporter.java:135)
2d9a80> 	at com.occamlab.te.TECore.execute(TECore.java:359)
2d9a80> 	at com.occamlab.te.TECore.run(TECore.java:2505)
2d9a80> 	at java.lang.Thread.run(Thread.java:748)
```

It seems that the problem occurs during generation of EarlReport.
Root cause is most likely that the log files contain data which are referenced in GetCoverage responses making the files quite large.

Can currently be reproduced with http://conformance.rasdaman.com/rasdaman/ows?service=WCS&version=2.0.1&request=GetCapabilities.

**Comment by bpross-52n** [comment]
This needs to be moved to TEAM Engine. There the XMLParser class tries to parse a w3c.Document from a GetCoverage URL. The coverages size is 183 MB.  I'd suggest to use a stream based XML parser instead.

**Comment by pebau** [comment]
Two comments, FWIW:

- reproducing coverages in the log file should be removed, given that coverages generally are "bigger data"
- that said, I see no harm in restricting test coverages to some maximum size (say, 10 MB or even 1 MB), and communicate this to compliance testers: the tests inspect functional behavior, which is independent from the volume.
