### ISSUE TITLE
Test of extension Interpolation fails with NPE

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs20#60]
## Setup
SUT: http://conformance.rasdaman.com/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1
Selected CCs: only `interpolation`
Tested locally with docker environment 
  * ETS WCS 2. 0 1.13-SNAPSHOT (includes PR #48)
 * TEAM Engine 5.2

## Testfailure
" Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.reflect.InvocationTargetException"
 *  Failure from error log: 
```
Caused by: java.lang.NullPointerException
        at com.occamlab.te.TECore.updateParentTestResult(TECore.java:1051)
        at com.occamlab.te.TECore.callTest(TECore.java:1024)
        at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
        at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
        at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
        ... 76 more
```

**Comment by bangph** [comment]
@lgoltz: The endpoint (http://moon.planetserver:8084/rasdaman/ows) is our test service temporarily (i.e: it can be closed anytime). If you want to test with rasdaman WCS 2.0.1 then please use the official one which I maintain: http://conformance.rasdaman.com/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1

**Comment by lgoltz** [comment]
@bangph Thanks for the hint. I've changed the description.

**Comment by dstenger** [comment]
Fix successfully tested with http://conformance.rasdaman.com/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1.
No NPE occurs in log any more.
